### PR TITLE
add alternative railroad library

### PR DESCRIPTION
**Pull request by Floffah**
this is a suggestion but you can put this where you like

### CODE REVIEW

**Comment by kach** [comment]
You should update the docs by updating the markdown source in `md` and then running `npm run make`. That way the markdown and html stay in sync!

**Comment by kach** [comment]
PS do you have an online example of better-nearley-railroad output?

**Comment by Floffah** [comment]
no but i can make one

**Comment by Floffah** [comment]
I have put 2 examples of outputs [here](https://floffah.github.io/better-nearley-railroad/)

**Comment by kach** [comment]
Very nice! Instead of "(lexer)" you may consider prefixing that symbol with "%".

Once you update the PR to change the markdown and recompile, I'll merge it. Also, to attract more users you can be more specific about the additional features you provide (as opposed to simply "more in-depth").

**Comment by Floffah** [comment]
I cant actually get the nearley dependencies to install but i can give it ago :) also i will write a list of added features rn

**Comment by Floffah** [comment]
for some reason this seems to have bumped the docs version from 2.19.4 to 2.19.5

**Comment by Floffah** [comment]
ok ive tried to fix as much as i could this is confusion

**Comment by kach** [comment]
Okay, I separately added it to the docs. Thanks for your contribution!

**Comment by Floffah** [comment]
thank you!

**Pull request closed without merging**
